spring:
#  profiles:
#    active:
  output:
    ansi:
      enabled: always
  batch:
    job:
      names: ${job.name:helloWorldJob}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mariadb://t2.yejin.site:3306/batch_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: yejin
    password: yejin1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    com.ll.exam : DEBUG
    # springframework: DEBUG

